[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "planetarypy"
version = "0.2.0"
description = "Core package for planetary data tools."
readme = "README.rst"
requires-python = ">= 3.9, <4"
license = {text = "BSD license"}
authors = [
    {name = "Planetarypy Developers", email = "69774+michaelaye@users.noreply.github.com"}
]
keywords = ["planetarypy", "planetary", "space", "science"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "tomlkit",
    "requests",
    "tqdm",
    "pandas",
    "astropy",
    "spiceypy",
    "yarl",
    "matplotlib",
    "planets",
]

[project.urls]
Homepage = "https://github.com/planetarypy/planetarypy"
Repository = "https://github.com/planetarypy/planetarypy"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "build",
    "twine",
    "pip-tools",
    "make",
]

[project.scripts]
planetarypy = "planetarypy.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/planetarypy"]

[tool.hatch.build]
include = [
    "src/planetarypy/**/*.py",
    "src/planetarypy/**/*.pyd",
    "src/planetarypy/**/*.so",
    "LICENSE",
    "README.rst",
    "HISTORY.rst",
]

[tool.pytest]
testpaths = ["tests"]
addopts = "--ignore=setup.py"

[tool.flake8]
exclude = ["docs"]
max-line-length = 88
extend-ignore = ["E203", "E701"]

[tool.bumpversion]
current_version = "0.2.0"
commit = true
tag = true