"""Foundation classes for ``planetarypy.constants``.

Three types live here:

- :class:`Constant`  — a thin ``astropy.units.Quantity`` subclass that
  carries provenance metadata (PCK source, IAU edition, body name,
  description, reference). Used for every value that comes directly out
  of a PCK kernel.
- :class:`Body`      — a frozen container of constants for one celestial
  body (Sun, planet, moon, asteroid, comet). Generated by the
  regenerator script, never hand-edited.
- :class:`BodyRegistry` — a dict of bodies keyed by NAIF ID, with
  case-insensitive name lookup and class-based filtering helpers.

See ``docs/explanation/constants_design.qmd`` for the design rationale.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterable, Optional

import numpy as np
import astropy.units as u


# ── Constant ────────────────────────────────────────────────────────────


class Constant(u.Quantity):
    """A ``Quantity`` with attached PCK provenance metadata.

    Behaves like any other :class:`astropy.units.Quantity` for math and
    unit operations — composes in formulas, supports ``.to()``, slices,
    etc. The extra fields are read-only after construction:

    - ``name``         — short field name, e.g. ``"GM"``, ``"radii"``
    - ``body``         — body name, e.g. ``"Mars"``
    - ``description``  — human-readable description
    - ``reference``    — citation string (IAU report)
    - ``iau_year``     — IAU edition year (e.g. ``2015``)
    - ``pck_source``   — source PCK filename (e.g. ``"pck00011.tpc"``)

    Math operations (``+``, ``-``, ``*``, ``/``, ``**``, ufuncs) preserve
    the metadata of the *first* operand on a best-effort basis. Use
    ``.value`` if you want a clean numeric result without metadata; use
    the metadata on a value that came directly from PCK.
    """

    def __new__(
        cls,
        value,
        unit=None,
        *,
        name: str = "",
        body: str = "",
        description: str = "",
        reference: str = "",
        iau_year: int = 0,
        pck_source: str = "",
        **kwargs,
    ):
        # Accept the same shapes as Quantity: a Quantity, a (value, unit)
        # pair, or a bare value with separate unit.
        if isinstance(value, u.Quantity):
            inst = u.Quantity.__new__(
                cls, value.value, value.unit, **kwargs
            )
        else:
            inst = u.Quantity.__new__(cls, value, unit, **kwargs)
        inst._meta = {
            "name": name,
            "body": body,
            "description": description,
            "reference": reference,
            "iau_year": int(iau_year),
            "pck_source": pck_source,
        }
        return inst

    def __array_finalize__(self, obj):
        super().__array_finalize__(obj)
        if obj is None:
            return
        # Propagate metadata for view operations (slicing, copying, math
        # via __array_wrap__). Falls back to empty defaults if obj has
        # no metadata (unlikely but defensive).
        self._meta = getattr(obj, "_meta", {
            "name": "", "body": "", "description": "",
            "reference": "", "iau_year": 0, "pck_source": "",
        })

    # Read-only accessors. Don't expose direct dict mutation.
    @property
    def name(self) -> str: return self._meta.get("name", "")
    @property
    def body(self) -> str: return self._meta.get("body", "")
    @property
    def description(self) -> str: return self._meta.get("description", "")
    @property
    def reference(self) -> str: return self._meta.get("reference", "")
    @property
    def iau_year(self) -> int: return self._meta.get("iau_year", 0)
    @property
    def pck_source(self) -> str: return self._meta.get("pck_source", "")

    def __repr__(self) -> str:
        # If we have provenance, surface it. Otherwise behave like a
        # plain Quantity (no "Constant ..." wrapper) so users don't see
        # a bare value claiming a type that's not telling them anything.
        body = self._meta.get("body", "")
        name = self._meta.get("name", "")
        year = self._meta.get("iau_year", 0)
        if body and name and year:
            try:
                val = np.asarray(self)
                if val.shape == ():
                    val_repr = f"{float(val):.6g}"
                else:
                    val_repr = np.array2string(val, precision=6, separator=", ")
            except Exception:
                val_repr = repr(np.asarray(self))
            return (
                f"<Constant {body}.{name} = {val_repr} {self.unit}  "
                f"(IAU {year})>"
            )
        # Fall through to a plain Quantity-style repr — same content,
        # no "Constant" prefix.
        return repr(u.Quantity(self))


# ── Body ────────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class Body:
    """All constants for one celestial body.

    Values that came directly from the PCK are :class:`Constant`
    instances (with provenance metadata); derived values (``mass``,
    ``density``) are plain ``Quantity`` properties computed lazily from
    the PCK constants and ``astropy.constants.G``.

    Optional fields default to ``None`` — not every body in the PCK has
    every field (e.g. minor moons often have ``radii`` only).
    """

    name: str
    """Canonical PCK name (uppercase, e.g. ``"MARS"``)."""

    naif_id: int
    """NAIF integer id (e.g. ``499`` for Mars)."""

    body_class: str
    """One of ``"sun"``, ``"planet"``, ``"moon"``, ``"asteroid"``, ``"comet"``."""

    parent: Optional[int] = None
    """NAIF id of parent planet for moons; ``None`` otherwise."""

    dwarf_planet: bool = False
    """``True`` for IAU-classified dwarf planets (Pluto, Ceres, …)."""

    mission_visited: bool = False
    """``True`` for small bodies that have been flown by, orbited, or landed on."""

    # ── Layer 1: static physical ────────────────────────────────────────
    radii: Optional[Constant] = None
    GM: Optional[Constant] = None
    long_axis: Optional[Constant] = None

    # ── Layer 2: orientation at J2000 (scalar Constants) ────────────────
    pole_ra: Optional[Constant] = None
    pole_dec: Optional[Constant] = None
    pm: Optional[Constant] = None
    rotation_rate: Optional[Constant] = None

    # ── Layer 3: full polynomial coefficients (J2000, rate, quad) ───────
    pole_ra_coeffs: Optional[tuple] = None
    pole_dec_coeffs: Optional[tuple] = None
    pm_coeffs: Optional[tuple] = None

    # ── Derived (computed at module-build time, baked in) ───────────────
    mean_radius: Optional[Constant] = None
    volume_radius: Optional[Constant] = None
    flattening: Optional[float] = None

    # ── Derived (computed lazily, depend on astropy.constants.G) ────────

    @property
    def mass(self) -> Optional[u.Quantity]:
        """Body mass derived from ``GM`` and ``astropy.constants.G``.

        Returns plain ``Quantity`` (not ``Constant``) — provenance is
        "see GM and astropy's G". Returns ``None`` if ``GM`` is unknown.
        """
        if self.GM is None:
            return None
        from astropy.constants import G
        result = (self.GM / G).to(u.kg)
        # Demote to plain Quantity: derived values shouldn't claim PCK
        # provenance they don't directly have.
        return u.Quantity(result.value, result.unit)

    @property
    def density(self) -> Optional[u.Quantity]:
        """Mean density derived from ``mass`` and triaxial ``radii``.

        Volume is computed as a triaxial ellipsoid:
        ``V = (4/3) * π * a * b * c``. Returns ``None`` if either ``GM``
        or ``radii`` is unknown.
        """
        if self.GM is None or self.radii is None:
            return None
        a, b, c = self.radii
        volume = (4.0 / 3.0) * np.pi * a * b * c
        result = (self.mass / volume).to(u.kg / u.m ** 3)
        return u.Quantity(result.value, result.unit)

    def __repr__(self) -> str:
        return (
            f"<Body {self.name} (NAIF {self.naif_id}, "
            f"class={self.body_class!r})>"
        )


# ── BodyRegistry ────────────────────────────────────────────────────────


class BodyRegistry(dict):
    """Dict of bodies keyed by NAIF ID, with name + class-based lookup.

    Indexable by either NAIF id (``registry[499]``) or name
    (``registry["MARS"]``, ``registry["mars"]`` — case-insensitive).

    Use :meth:`by_class` to filter by ``body_class`` and optional parent.
    """

    def __init__(self, bodies: Optional[dict] = None):
        super().__init__(bodies or {})
        self._refresh_name_index()

    def _refresh_name_index(self) -> None:
        self._by_name = {
            b.name.upper(): b for b in self.values()
            if isinstance(b, Body)
        }

    def __getitem__(self, key):
        if isinstance(key, int):
            return super().__getitem__(key)
        if isinstance(key, str):
            try:
                return self._by_name[key.upper()]
            except KeyError:
                raise KeyError(key) from None
        raise KeyError(key)

    def __contains__(self, key) -> bool:
        if isinstance(key, int):
            return super().__contains__(key)
        if isinstance(key, str):
            return key.upper() in self._by_name
        return False

    def find(self, query) -> Optional[Body]:
        """Best-effort lookup by NAIF id or case-insensitive name.

        Returns ``None`` instead of raising on miss, unlike ``__getitem__``.
        """
        try:
            return self[query]
        except KeyError:
            return None

    def by_class(
        self,
        body_class: str,
        parent: Optional[object] = None,
    ) -> list[Body]:
        """Filter to a body class, optionally restricted to one parent.

        ``parent`` may be a NAIF id (``699``), a body name (``"Saturn"``),
        or a :class:`Body` instance.
        """
        results = [b for b in self.values()
                   if isinstance(b, Body) and b.body_class == body_class]
        if parent is None:
            return results

        if isinstance(parent, Body):
            parent_id = parent.naif_id
        elif isinstance(parent, int):
            parent_id = parent
        elif isinstance(parent, str):
            try:
                parent_id = self._by_name[parent.upper()].naif_id
            except KeyError:
                return []
        else:
            raise TypeError(
                f"parent must be int, str, or Body; got {type(parent).__name__}"
            )
        return [b for b in results if b.parent == parent_id]
