"""Foundation classes for ``planetarypy.constants``.

Three types live here:

- :class:`Constant`  — a thin ``astropy.units.Quantity`` subclass that
  carries provenance metadata (PCK source, IAU edition, body name,
  description, reference). Used for every value that comes directly out
  of a PCK kernel.
- :class:`Body`      — a frozen container of constants for one celestial
  body (Sun, planet, moon, asteroid, comet). Generated by the
  regenerator script, never hand-edited.
- :class:`BodyRegistry` — a dict of bodies keyed by NAIF ID, with
  case-insensitive name lookup and class-based filtering helpers.

See ``docs/explanation/constants_design.qmd`` for the design rationale.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterable, Optional

import numpy as np
import astropy.units as u


# Julian century — 100 Julian years, the natural unit for PCK polynomial
# rate coefficients (POLE_RA, POLE_DEC, quadratic terms). astropy's
# ``u.cy`` is the "cycle" unit (rotational measure), not century, and
# ``100 * u.year`` reduces numerically to ``0.01 * yr`` on display. We
# register a named unit here once for the whole subpackage so
# generated iauNNNN.py modules can import it without duplicate-
# registration errors. exclude_prefixes prevents auto-generation of
# kilo-/mega- variants we don't want polluting the namespace.
century = u.def_unit("century", 100 * u.year)


# ── Constant ────────────────────────────────────────────────────────────


class Constant(u.Quantity):
    """A ``Quantity`` with attached PCK provenance metadata.

    Behaves like any other :class:`astropy.units.Quantity` for math
    and unit operations — composes in formulas, supports ``.to()``,
    slices, etc. View operations (slicing, copying, ufuncs) propagate
    metadata; explicitly demote to plain ``Quantity`` if you want a
    metadata-free value.

    Metadata fields (all defaulting to empty/zero):
    ``name``, ``body``, ``description``, ``reference``, ``iau_year``,
    ``pck_source``.
    """

    # Field name → default. Drives both __new__ propagation and
    # __array_finalize__ inheritance from view-source objects.
    _META: dict[str, object] = {
        "name": "", "body": "", "description": "",
        "reference": "", "iau_year": 0, "pck_source": "",
    }

    def __new__(cls, value, unit=None, *,
                name="", body="", description="",
                reference="", iau_year=0, pck_source=""):
        if isinstance(value, u.Quantity):
            inst = u.Quantity.__new__(cls, value.value, value.unit)
        else:
            inst = u.Quantity.__new__(cls, value, unit)
        inst.name = name
        inst.body = body
        inst.description = description
        inst.reference = reference
        inst.iau_year = int(iau_year)
        inst.pck_source = pck_source
        return inst

    def __array_finalize__(self, obj):
        super().__array_finalize__(obj)
        if obj is None:
            return
        for field, default in self._META.items():
            setattr(self, field, getattr(obj, field, default))

    def __repr__(self) -> str:
        if self.body and self.name and self.iau_year:
            arr = np.asarray(self)
            v = (f"{float(arr):.6g}" if arr.shape == ()
                 else np.array2string(arr, precision=6, separator=", "))
            return (f"<Constant {self.body}.{self.name} = {v} {self.unit}  "
                    f"(IAU {self.iau_year})>")
        return repr(u.Quantity(self))


# ── Body ────────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class Body:
    """All constants for one celestial body.

    Values that came directly from the PCK are :class:`Constant`
    instances (with provenance metadata); derived values (``mass``,
    ``density``) are plain ``Quantity`` properties computed lazily from
    the PCK constants and ``astropy.constants.G``.

    Optional fields default to ``None`` — not every body in the PCK has
    every field (e.g. minor moons often have ``radii`` only).
    """

    name: str
    """Canonical PCK name (uppercase, e.g. ``"MARS"``)."""

    naif_id: int
    """NAIF integer id (e.g. ``499`` for Mars)."""

    body_class: str
    """One of ``"sun"``, ``"planet"``, ``"moon"``, ``"asteroid"``, ``"comet"``."""

    parent: Optional[int] = None
    """NAIF id of parent planet for moons; ``None`` otherwise."""

    dwarf_planet: bool = False
    """``True`` for IAU-classified dwarf planets (Pluto, Ceres, …)."""

    mission_visited: bool = False
    """``True`` for small bodies that have been flown by, orbited, or landed on."""

    # ── Layer 1: static physical ────────────────────────────────────────
    radii: Optional[Constant] = None
    GM: Optional[Constant] = None
    long_axis: Optional[Constant] = None

    # ── Layer 2: orientation at J2000 (scalar Constants) ────────────────
    pole_ra: Optional[Constant] = None
    pole_dec: Optional[Constant] = None
    pm: Optional[Constant] = None
    rotation_rate: Optional[Constant] = None

    # ── Layer 3: full polynomial coefficients (J2000, rate, quad) ───────
    pole_ra_coeffs: Optional[tuple] = None
    pole_dec_coeffs: Optional[tuple] = None
    pm_coeffs: Optional[tuple] = None

    # ── Derived (computed at module-build time, baked in) ───────────────
    mean_radius: Optional[Constant] = None
    volume_radius: Optional[Constant] = None
    flattening: Optional[float] = None

    # ── Derived (computed lazily, depend on astropy.constants.G) ────────

    @property
    def mass(self) -> Optional[u.Quantity]:
        """Body mass derived from ``GM`` and ``astropy.constants.G``.

        Plain ``Quantity`` — derived values shouldn't claim PCK
        provenance they don't have. ``None`` when ``GM`` is unknown.
        """
        if self.GM is None:
            return None
        from astropy.constants import G
        return (self.GM / G).to(u.kg).value * u.kg

    @property
    def density(self) -> Optional[u.Quantity]:
        """Mean density from ``mass`` over the triaxial ellipsoid volume.

        ``V = (4/3) · π · a · b · c``. ``None`` when either ``GM`` or
        ``radii`` is unknown.
        """
        if self.GM is None or self.radii is None:
            return None
        a, b, c = self.radii
        volume = (4.0 / 3.0) * np.pi * a * b * c
        return (self.mass / volume).to(u.kg / u.m ** 3).value * u.kg / u.m ** 3

    def __repr__(self) -> str:
        return (
            f"<Body {self.name} (NAIF {self.naif_id}, "
            f"class={self.body_class!r})>"
        )


# ── BodyRegistry ────────────────────────────────────────────────────────


class BodyRegistry(dict):
    """Dict of bodies keyed by NAIF ID, with name + class-based lookup.

    Indexable by either NAIF id (``registry[499]``) or name
    (``registry["MARS"]``, ``registry["mars"]`` — case-insensitive).

    Use :meth:`by_class` to filter by ``body_class`` and optional parent.
    """

    def __init__(self, bodies: Optional[dict] = None):
        super().__init__(bodies or {})
        self._by_name = {b.name.upper(): b for b in self.values()
                         if isinstance(b, Body)}

    def __getitem__(self, key):
        if isinstance(key, str):
            try:
                return self._by_name[key.upper()]
            except KeyError:
                raise KeyError(key) from None
        return super().__getitem__(key)

    def __contains__(self, key) -> bool:
        if isinstance(key, str):
            return key.upper() in self._by_name
        return super().__contains__(key)

    def find(self, query) -> Optional[Body]:
        """Best-effort lookup by NAIF id or name; ``None`` on miss."""
        try:
            return self[query]
        except KeyError:
            return None

    def by_class(self, body_class: str, parent=None) -> list[Body]:
        """Filter by ``body_class``, optionally also by ``parent``.

        ``parent`` may be a NAIF id, a body name, or a :class:`Body`.
        """
        results = [b for b in self.values()
                   if isinstance(b, Body) and b.body_class == body_class]
        if parent is None:
            return results
        if isinstance(parent, Body):
            parent_id = parent.naif_id
        elif isinstance(parent, int):
            parent_id = parent
        elif isinstance(parent, str):
            found = self.find(parent)
            if found is None:
                return []
            parent_id = found.naif_id
        else:
            raise TypeError(
                f"parent must be int, str, or Body; got {type(parent).__name__}"
            )
        return [b for b in results if b.parent == parent_id]
