"""Foundation classes for ``planetarypy.constants``.

Three types live here:

- :class:`Constant`  — a thin ``astropy.units.Quantity`` subclass that
  carries provenance metadata (PCK source, IAU edition, body name,
  description, reference). Used for every value that comes directly out
  of a PCK kernel.
- :class:`Body`      — a frozen container of constants for one celestial
  body (Sun, planet, moon, asteroid, comet). Generated by the
  regenerator script, never hand-edited.
- :class:`BodyRegistry` — a dict of bodies keyed by NAIF ID, with
  case-insensitive name lookup and class-based filtering helpers.

See ``docs/explanation/constants_design.qmd`` for the design rationale.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterable, Optional

import numpy as np
import astropy.units as u


# Julian century — 100 Julian years, the natural unit for PCK polynomial
# rate coefficients (POLE_RA, POLE_DEC, quadratic terms). astropy's
# ``u.cy`` is the "cycle" unit (rotational measure), not century, and
# ``100 * u.year`` reduces numerically to ``0.01 * yr`` on display. We
# register a named unit here once for the whole subpackage so
# generated iauNNNN.py modules can import it without duplicate-
# registration errors. exclude_prefixes prevents auto-generation of
# kilo-/mega- variants we don't want polluting the namespace.
century = u.def_unit("century", 100 * u.year)


# Publication dates of the IAU PCK editions we ship. ``Body.at_time``
# uses these to pick the edition that would have been current on the
# requested date — older dates get the older edition, dates before any
# PCK publication fall back to NSSDC entirely.
#
# Sorted *oldest-first* so resolution iterates and picks the latest
# edition published on-or-before the target date.
_PCK_EDITION_DATES: list[tuple[str, int]] = [
    ("2010-10-21", 2009),   # pck00010.tpc — Archinal et al. 2011
    ("2018-09-20", 2015),   # pck00011.tpc — Archinal et al. 2018
]
_PCK_VALIDITY_START = _PCK_EDITION_DATES[0][0]

# Set of dataclass-field names whose default values come from PCK. When
# Body.at_time is called and PCK is valid for the date, these fields
# are kept from the source Body rather than overlaid from NSSDC.
_PCK_DERIVED_FIELDS: frozenset[str] = frozenset({
    "radii", "GM", "long_axis",
    "pole_ra", "pole_dec", "pm", "rotation_rate",
    "pole_ra_coeffs", "pole_dec_coeffs", "pm_coeffs",
    "mean_radius", "volume_radius", "flattening",
})


# ── Constant ────────────────────────────────────────────────────────────


class Constant(u.Quantity):
    """A ``Quantity`` with attached PCK provenance metadata.

    Behaves like any other :class:`astropy.units.Quantity` for math
    and unit operations — composes in formulas, supports ``.to()``,
    slices, etc. View operations (slicing, copying, ufuncs) propagate
    metadata; explicitly demote to plain ``Quantity`` if you want a
    metadata-free value.

    Metadata fields (all defaulting to empty/zero):
    ``name``, ``body``, ``description``, ``reference``, ``iau_year``,
    ``source``.
    """

    # Field name → default. Drives both __new__ propagation and
    # __array_finalize__ inheritance from view-source objects.
    _META: dict[str, object] = {
        "name": "", "body": "", "description": "",
        "reference": "", "iau_year": 0, "source": "",
    }

    def __new__(cls, value, unit=None, *,
                name="", body="", description="",
                reference="", iau_year=0, source=""):
        if isinstance(value, u.Quantity):
            inst = u.Quantity.__new__(cls, value.value, value.unit)
        else:
            inst = u.Quantity.__new__(cls, value, unit)
        inst.name = name
        inst.body = body
        inst.description = description
        inst.reference = reference
        inst.iau_year = int(iau_year)
        inst.source = source
        return inst

    def __array_finalize__(self, obj):
        super().__array_finalize__(obj)
        if obj is None:
            return
        for field, default in self._META.items():
            setattr(self, field, getattr(obj, field, default))

    def __repr__(self) -> str:
        # Rich repr requires body+name to identify *what* the value is.
        # The provenance tag prefers IAU year (PCK-sourced constants
        # carry one) and falls back to the raw source string for
        # NSSDC-sourced constants where iau_year is intentionally 0.
        if self.body and self.name and (self.iau_year or self.source):
            arr = np.asarray(self)
            v = (f"{float(arr):.6g}" if arr.shape == ()
                 else np.array2string(arr, precision=6, separator=", "))
            tag = f"IAU {self.iau_year}" if self.iau_year else self.source
            return (f"<Constant {self.body}.{self.name} = {v} {self.unit}  "
                    f"({tag})>")
        return repr(u.Quantity(self))


# ── Body ────────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class Body:
    """All constants for one celestial body.

    Values that came directly from the PCK are :class:`Constant`
    instances (with provenance metadata); derived values (``mass``,
    ``density``) are plain ``Quantity`` properties computed lazily from
    the PCK constants and ``astropy.constants.G``.

    Optional fields default to ``None`` — not every body in the PCK has
    every field (e.g. minor moons often have ``radii`` only).
    """

    name: str
    """Canonical PCK name (uppercase, e.g. ``"MARS"``)."""

    naif_id: int
    """NAIF integer id (e.g. ``499`` for Mars)."""

    body_class: str
    """One of ``"sun"``, ``"planet"``, ``"moon"``, ``"asteroid"``, ``"comet"``."""

    parent: Optional[int] = None
    """NAIF id of parent planet for moons; ``None`` otherwise."""

    dwarf_planet: bool = False
    """``True`` for IAU-classified dwarf planets (Pluto, Ceres, …)."""

    mission_visited: bool = False
    """``True`` for small bodies that have been flown by, orbited, or landed on."""

    # ── Layer 1: static physical ────────────────────────────────────────
    radii: Optional[Constant] = None
    GM: Optional[Constant] = None
    long_axis: Optional[Constant] = None

    # ── Layer 2: orientation at J2000 (scalar Constants) ────────────────
    pole_ra: Optional[Constant] = None
    pole_dec: Optional[Constant] = None
    pm: Optional[Constant] = None
    rotation_rate: Optional[Constant] = None

    # ── Layer 3: full polynomial coefficients (J2000, rate, quad) ───────
    pole_ra_coeffs: Optional[tuple] = None
    pole_dec_coeffs: Optional[tuple] = None
    pm_coeffs: Optional[tuple] = None

    # ── Derived (computed at module-build time, baked in) ───────────────
    mean_radius: Optional[Constant] = None
    volume_radius: Optional[Constant] = None
    flattening: Optional[float] = None

    # ── NSSDC-sourced fields (typically not in PCK) ─────────────────────
    # These are populated from the latest NSSDC fact-sheet capture during
    # build-time merge. Default to None for bodies the NSSDC archive
    # doesn't cover (most asteroids/moons; only major planets + Sun + Moon
    # + class summaries have NSSDC fact sheets).
    equatorial_radius: Optional[Constant] = None
    polar_radius: Optional[Constant] = None
    volumetric_mean_radius: Optional[Constant] = None
    core_radius: Optional[Constant] = None
    ellipticity: Optional[Constant] = None
    mean_density: Optional[Constant] = None
    surface_gravity: Optional[Constant] = None
    surface_acceleration: Optional[Constant] = None
    surface_acceleration_eq: Optional[Constant] = None
    surface_acceleration_pole: Optional[Constant] = None
    escape_velocity: Optional[Constant] = None
    bond_albedo: Optional[Constant] = None
    geometric_albedo: Optional[Constant] = None
    v_band_magnitude: Optional[Constant] = None
    solar_irradiance: Optional[Constant] = None
    black_body_temperature: Optional[Constant] = None
    topographic_range: Optional[Constant] = None
    moment_of_inertia: Optional[Constant] = None
    J2: Optional[Constant] = None
    number_of_satellites: Optional[Constant] = None
    has_ring_system: Optional[Constant] = None  # numeric bool: 1.0 / 0.0

    # Orbital
    semimajor_axis: Optional[Constant] = None
    sidereal_orbit_period: Optional[Constant] = None
    tropical_orbit_period: Optional[Constant] = None
    perihelion: Optional[Constant] = None
    aphelion: Optional[Constant] = None
    synodic_period: Optional[Constant] = None
    mean_orbital_velocity: Optional[Constant] = None
    max_orbital_velocity: Optional[Constant] = None
    min_orbital_velocity: Optional[Constant] = None
    orbit_inclination: Optional[Constant] = None
    orbit_eccentricity: Optional[Constant] = None
    sidereal_rotation_period: Optional[Constant] = None
    length_of_day: Optional[Constant] = None
    obliquity_to_orbit: Optional[Constant] = None
    inclination_of_equator: Optional[Constant] = None

    # Atmospheric
    surface_pressure: Optional[Constant] = None
    surface_density: Optional[Constant] = None
    scale_height: Optional[Constant] = None
    average_temperature: Optional[Constant] = None
    mean_molecular_weight: Optional[Constant] = None

    # Bulk (overlap-with-PCK; populated from NSSDC only when PCK doesn't
    # provide the same — used by the regenerator's merge step).
    volume: Optional[Constant] = None

    # ── Derived (computed lazily, depend on astropy.constants.G) ────────

    @property
    def mass(self) -> Optional[u.Quantity]:
        """Body mass derived from ``GM`` and ``astropy.constants.G``.

        Plain ``Quantity`` — derived values shouldn't claim PCK
        provenance they don't have. ``None`` when ``GM`` is unknown.
        """
        if self.GM is None:
            return None
        from astropy.constants import G
        return (self.GM / G).to(u.kg).value * u.kg

    @property
    def density(self) -> Optional[u.Quantity]:
        """Mean density from ``mass`` over the triaxial ellipsoid volume.

        ``V = (4/3) · π · a · b · c``. ``None`` when either ``GM`` or
        ``radii`` is unknown.
        """
        if self.GM is None or self.radii is None:
            return None
        a, b, c = self.radii
        volume = (4.0 / 3.0) * np.pi * a * b * c
        return (self.mass / volume).to(u.kg / u.m ** 3).value * u.kg / u.m ** 3

    def at_time(self, date) -> "Body":
        """Return a snapshot Body with fields resolved as of ``date``.

        Resolution rules:

        - **PCK fields** (radii, GM, pole_*, rotation_rate, ...): pulled
          from whichever IAU PCK edition was current on ``date``. IAU
          2009 PCK published 2010-10-21; IAU 2015 PCK published
          2018-09-20. Before 2010-10-21 no PCK existed → NSSDC fills in.
        - **NSSDC-only fields** (bond_albedo, surface_pressure, ...):
          overlaid from NSSDC at the given date.

        ``date`` accepts ``"2001"`` / ``"2001-06"`` / ``"2001-06-15"`` —
        year/year-month resolve to end-of-period.

        Returns a fresh frozen Body; ``self`` is unmodified.
        """
        from planetarypy.constants.nssdc import _loader

        archive_body = self.name.lower()
        nssdc_has_body = archive_body in _loader.known_bodies()

        iso = _loader.normalize_date(str(date))

        # Determine which IAU edition's PCK fields apply on this date.
        # ``edition_year`` is None when no PCK had been published yet
        # (NSSDC will need to fill the overlap fields).
        edition_year: Optional[int] = None
        for pub_date, year in _PCK_EDITION_DATES:
            if iso >= pub_date:
                edition_year = year
        pck_is_valid = edition_year is not None

        new_kwargs: dict = {}

        # Step 1 — if the edition for the date differs from this body's
        # default edition, pull PCK fields from that edition's Body.
        # The default (latest) is IAU 2015 = the body the user imports
        # bare; only pre-2018 dates need to swap in IAU 2009 values.
        if pck_is_valid and edition_year != _PCK_EDITION_DATES[-1][1]:
            from importlib import import_module
            edition_mod = import_module(
                f"planetarypy.constants.iau{edition_year}")
            edition_body = edition_mod.bodies.find(self.naif_id)
            if edition_body is not None:
                for field_name in _PCK_DERIVED_FIELDS:
                    if field_name not in self.__dataclass_fields__:
                        continue
                    val = getattr(edition_body, field_name, None)
                    if val is not None:
                        new_kwargs[field_name] = val

        # Step 2 — overlay NSSDC for everything NSSDC has, skipping PCK
        # fields we already sourced above.
        if nssdc_has_body:
            for field_name in _loader.known_fields(archive_body):
                if field_name not in self.__dataclass_fields__:
                    continue
                # Skip PCK overlap fields if PCK is valid AND we have one.
                if field_name in _PCK_DERIVED_FIELDS and pck_is_valid:
                    continue
                rec = _loader.at_date(archive_body, field_name, iso)
                if rec is None:
                    continue
                qty = _loader.coerce_value(rec.value, rec.unit)
                if qty is None:
                    continue
                new_kwargs[field_name] = Constant(
                    qty,
                    name=rec.field, body=self.name.title(),
                    description=f"NSSDC field '{rec.field}' (raw='{rec.value}', unit='{rec.unit}')",
                    reference=(
                        "NASA NSSDC Planetary Fact Sheets, Williams D.R. (NSSDC, GSFC), "
                        "https://nssdc.gsfc.nasa.gov/planetary/factsheet/"
                    ),
                    iau_year=0,
                    source=rec.source_string(),
                )

        if not new_kwargs:
            return self

        from dataclasses import replace
        return replace(self, **new_kwargs)

    def __repr__(self) -> str:
        return (
            f"<Body {self.name} (NAIF {self.naif_id}, "
            f"class={self.body_class!r})>"
        )


# ── BodyRegistry ────────────────────────────────────────────────────────


class BodyRegistry(dict):
    """Dict of bodies keyed by NAIF ID, with name + class-based lookup.

    Indexable by either NAIF id (``registry[499]``) or name
    (``registry["MARS"]``, ``registry["mars"]`` — case-insensitive).

    Use :meth:`by_class` to filter by ``body_class`` and optional parent.
    """

    def __init__(self, bodies: Optional[dict] = None):
        super().__init__(bodies or {})
        self._by_name = {b.name.upper(): b for b in self.values()
                         if isinstance(b, Body)}

    def __getitem__(self, key):
        if isinstance(key, str):
            try:
                return self._by_name[key.upper()]
            except KeyError:
                raise KeyError(key) from None
        return super().__getitem__(key)

    def __contains__(self, key) -> bool:
        if isinstance(key, str):
            return key.upper() in self._by_name
        return super().__contains__(key)

    def find(self, query) -> Optional[Body]:
        """Best-effort lookup by NAIF id or name; ``None`` on miss."""
        try:
            return self[query]
        except KeyError:
            return None

    def by_class(self, body_class: str, parent=None) -> list[Body]:
        """Filter by ``body_class``, optionally also by ``parent``.

        ``parent`` may be a NAIF id, a body name, or a :class:`Body`.
        """
        results = [b for b in self.values()
                   if isinstance(b, Body) and b.body_class == body_class]
        if parent is None:
            return results
        if isinstance(parent, Body):
            parent_id = parent.naif_id
        elif isinstance(parent, int):
            parent_id = parent
        elif isinstance(parent, str):
            found = self.find(parent)
            if found is None:
                return []
            parent_id = found.naif_id
        else:
            raise TypeError(
                f"parent must be int, str, or Body; got {type(parent).__name__}"
            )
        return [b for b in results if b.parent == parent_id]
