# exceptions { #planetarypy.exceptions }

`exceptions`

PlanetarPy exceptions.

## Classes

| Name | Description |
| --- | --- |
| [Error](#planetarypy.exceptions.Error) | Base class for exceptions in this module. |
| [GeoTransformNotSetError](#planetarypy.exceptions.GeoTransformNotSetError) | Exception raised when a GeoTransform is not set. |
| [ProjectionNotSetError](#planetarypy.exceptions.ProjectionNotSetError) | Exception raised when a projection is not set. |
| [SomethingNotSetError](#planetarypy.exceptions.SomethingNotSetError) | Exception raised for errors in the input of transformations. |
| [SpicerError](#planetarypy.exceptions.SpicerError) | Base class for exceptions in this module. |

### Error { #planetarypy.exceptions.Error }

```python
exceptions.Error()
```

[[source]](https://github.com/michaelaye/planetarypy/blob/main/src/planetarypy/exceptions.py#L16-L19){.source-link target="_blank"}

Base class for exceptions in this module.

### GeoTransformNotSetError { #planetarypy.exceptions.GeoTransformNotSetError }

```python
exceptions.GeoTransformNotSetError(where)
```

[[source]](https://github.com/michaelaye/planetarypy/blob/main/src/planetarypy/exceptions.py#L48-L52){.source-link target="_blank"}

Exception raised when a GeoTransform is not set.

### ProjectionNotSetError { #planetarypy.exceptions.ProjectionNotSetError }

```python
exceptions.ProjectionNotSetError(where)
```

[[source]](https://github.com/michaelaye/planetarypy/blob/main/src/planetarypy/exceptions.py#L41-L45){.source-link target="_blank"}

Exception raised when a projection is not set.

### SomethingNotSetError { #planetarypy.exceptions.SomethingNotSetError }

```python
exceptions.SomethingNotSetError(where, what)
```

[[source]](https://github.com/michaelaye/planetarypy/blob/main/src/planetarypy/exceptions.py#L22-L38){.source-link target="_blank"}

Exception raised for errors in the input of transformations.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type   | Description                 | Default    |
|--------|--------|-----------------------------|------------|
| where  |        | Where something is missing. | _required_ |
| what   |        | What is missing.            | _required_ |

### SpicerError { #planetarypy.exceptions.SpicerError }

```python
exceptions.SpicerError()
```

[[source]](https://github.com/michaelaye/planetarypy/blob/main/src/planetarypy/exceptions.py#L55-L58){.source-link target="_blank"}

Base class for exceptions in this module.