# FILE: .github/workflows/test.yaml
name: Run software tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Python ${{ matrix.python-version }} tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
      fail-fast: false
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        miniforge-version: latest
        activate-environment: test_env_py${{ matrix.python-version }}
        use-mamba: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: strict
        auto-activate-base: false
        conda-remove-defaults: true

    - name: Cache conda env
      uses: actions/cache@v3
      with:
        path: |
          ~/.conda/pkgs
          ~/.conda/envs
        key: conda-${{ runner.os }}-py${{ matrix.python-version }}-${{ github.sha }}
        restore-keys: |
          conda-${{ runner.os }}-py${{ matrix.python-version }}-
          conda-${{ runner.os }}-

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        # Install core dependencies via mamba first
        mamba install -y -c conda-forge tomlkit sh gdal
        
        # Run the installation script
        python install_dev_deps.py

    - name: Install package
      shell: bash -l {0}
      run: |
        pip install -e ".[spice]"

    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest --cov=src/planetarypy --cov-report=xml --cov-report=term

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: true
        name: codecov-py${{ matrix.python-version }}